services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
